# ===== Data =====
seed: 3407
timezone: "Asia/Bangkok"
frequency: "1H"

# Required columns (see data/schema.json)
columns:
  timestamp: timestamp
  site_id: category
  muc_thuong_luu: float
  muc_dang_binh_thuong: float
  muc_chet: float
  luu_luong_den: float
  tong_luong_xa: float
  xa_tran: float
  xa_nha_may: float
  so_cua_xa_sau: int
  so_cua_xa_mat: int
  # optional/known-future
  rain_forecast_mm: float
  planned_release_m3s: float

# Split (time-ordered)
split:
  train_ratio: 0.7
  val_ratio: 0.15
  # test = remainder

# Windowing
enc_len: 168           # 7 days history
dec_len: 336           # 14 days horizon (set 672 for 4 weeks)

# Quantiles & loss
quantiles: [0.1, 0.5, 0.9]

# Feature engineering
lags_hours: [1, 3, 6, 24, 48, 168]
roll_windows_hours: [3, 12, 24, 168]
roll_stats: ["mean", "std"]

# Training
batch_size: 64
max_epochs: 150 # 150
hidden_size: 160
attention_heads: 4
dropout: 0.1
learning_rate: 0.001
patience: 10

# Logging
mlflow:
  enabled: false
  tracking_uri: "file:./mlruns"
  experiment: "tft-waterlevel"

# Paths
paths:
  data_csv: "/kaggle/input/forecasting-data/sample.csv"
  artifacts_dir: "/kaggle/working/artifacts"
  models_dir: "/kaggle/working/models"
  best_ckpt: "/kaggle/working/models/best.ckpt"
  metadata_json: "/kaggle/working/models/metadata.json"